name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate synthetic data
        run: |
          if [ -f data/synthetic_generator.py ]; then python data/synthetic_generator.py; fi
          if [ -f data/synthetic_evidence.py ]; then python data/synthetic_evidence.py; fi
          if [ -f data/synthetic_claims.py ]; then python data/synthetic_claims.py; fi
      - name: Smoke run
        run: |
          if [ -f src/models/train.py ]; then python src/models/train.py; fi
          if [ -f src/inference/batch.py ]; then python src/inference/batch.py; fi
          if [ -f src/features/build_features.py ]; then python src/features/build_features.py --input data --out out.parquet; fi
      - uses: actions/upload-artifact@v4
        with: { name: ci-artifacts, path: out/** }
